# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 234310d5e46725bdd9d50f6911f191ca6f013b0bec302534c3044d3928ae5baf32af67acf321bd3af3ff9cef4e2481de1a5f3fdf73a75dcc57edab6186389861

test:
  secret_key_base: b6dd055c2751377102841e3b1c20a31f558441cd63944525a5f7f11390c756efecd454d472c9c3577ee8463344ad26108aa47714a0e36692d8c0f6a7600d0fd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
