# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1532daad24ed1ac8a99d02a93cddab545e18ecd01cd537059254f5b27a44c45158e6a377d8f1d32a014a6e89ba593f92ecdb5c27c3ada2c31c11e710b03e7177

test:
  secret_key_base: 0f14927e0400f1b6d943f23d2aef907a1ce9a37e4996694d5dc98479cb215026851d5c836ce4902c526423129c0c6a461c54855850fcab302166d82b497cf769

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
