# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b529ee8e4fc06039c82df9ddfe0f46793b1dfa576ad316b7bbcc982fc8caf3a20bf50d815186ec363dbda52c2d9b675d4c6f92c79d327dfd186bbe3bbe9bd7df

test:
  secret_key_base: 89cf5f1b289576434e6a5c84e8aec351e4679dc12a5c751b6e561d50416e5eaaf77f191556d4de791e2704c6882124ec4df3ff5c7e71fd863a2bebc91e873023

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
