# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f79a6a0d3df7f07e6b829856509d8c04f2e7397a74187abe1013e92561a48eec70152a900d1c1fb5773e3e4d8114c137854e32a4ba3001a10b6636f663f778f6

test:
  secret_key_base: 54362c883b2be204ff8873ae272ccc6f3930d81e79700a0b95a0fe7ce535923d9df101c2e4c9a308f55fdf6d2dbb25edc6bd165e839cb6964b0edf0c003e69cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
