---
development:
  cloud_name: hinchy
  api_key: '438463688933286'
  api_secret: q-hSKXdJqV6sTRXKYIXjAfbLVOY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hinchy
  api_key: '438463688933286'
  api_secret: q-hSKXdJqV6sTRXKYIXjAfbLVOY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hinchy
  api_key: '438463688933286'
  api_secret: q-hSKXdJqV6sTRXKYIXjAfbLVOY
  enhance_image_tag: true
  static_image_support: false